# Using Pandas

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [2]:
## Your Code here
import pandas as pd
df_cars= pd.read_csv("C:/Users/dengd/Documents/GitHub/IronDuo/Class_Materials/Pandas/Labs/data/vehicles.csv")
df_cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [3]:
# 1. How many observations does it have?
# df_cars_num = df_cars[df_cars.columns[0]].count() # .columns method get all columns then choose [0](the first one)
df_cars_num = df_cars["Make"].count()
print(f'There are :{df_cars_num} observations.')

# shape function 
df_cars.shape()

There are :35952 observations.

TypeError: 'tuple' object is not callable

In [ ]:
# 2. Look at all the columns: do you understand what they mean?
df_cars.info()

In [ ]:
# 3. Look at the raw data: do you see anything weird?
# I cannot see anything weird.

In [ ]:
# 4.Look at the data types: are they the expected ones for the information the column contains?
def unique_col_values():
    for column in df_cars:
        print("{} | {} | {}".format(
            df_cars[column].name, len(df_cars[column].unique()), df_cars[column].dtype
        ))

unique_col_values()

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

Note:
<br>Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Converting Gallons to Liters

1 Gallon = 3.78541 Liters

In [ ]:
# df_cars["Make"] =df_cars["Make"].str.replace(r'(.*)[dD]utton(.*)",'Dutton',regex =True)

In [ ]:
# Question1
# df_cars.loc[df_cars["Make"].str.find("Dutton")!=-1,"Make"]="Dutton"

In [4]:
df_cars.loc[df_cars["Make"].str.find("Dutton")!=-1]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,"E. P. Dutton, Inc.",Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,S and S Coach Company E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Superior Coaches Div E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

In [5]:
# Question2. Convert CO2 Emissions from Grams/Mile to Grams/Km
CO2_rename = df_cars.rename(columns ={"CO2 Emission Grams/Mile": "CO2 Emission Grams/Km"})
CO2_rename["CO2 Emission Grams/Km"]= CO2_rename["CO2 Emission Grams/Km"]/1.60934
CO2_rename

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,324.831736,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,345.133719,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,150.993575,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,152.857693,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,158.450048,1150

In [27]:
# Question3_method1
df_cars["Is Auto?"] = CO2_rename.loc[df_cars["Transmission"].str.find("Auto")!=-1,"Make"]= "Dutton"
df_cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Is Auto??,Is Auto?
0,Dutton,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,True,Dutton
1,Dutton,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,Dutton
2,Dutton,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,True,Dutton
3,Dutton,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,Dutton
4,Dutton,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,True,Dutton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,Dutton,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,Dutton
35948,Dutton,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,True,Dutton
35949,Dutton,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,Dutton
35950,Dutton,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,True,Dutton
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,False,Dutton

In [24]:
# Question1_ method2
df_cars["Is Auto??"] = df_cars["Transmission"].str.startswith("Auto")
df_cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Is Auto??,Is Auto?
0,Dutton,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,True,Dutton
1,Dutton,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,Dutton
2,Dutton,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,True,Dutton
3,Dutton,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,True,Dutton
4,Dutton,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,True,Dutton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,Dutton,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,Dutton
35948,Dutton,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,True,Dutton
35949,Dutton,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,True,Dutton
35950,Dutton,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,True,Dutton
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,False,Dutton

In [32]:
# Question4. convert MPG columns to km_per_liter
CO2_rename1 = CO2_rename.rename(columns ={"City MPG": "City KPL","Highway MPG": "Highway KPL","Combined MPG":"Combined KPL"})
CO2_rename1
CO2_rename2 = CO2_rename1[["City KPL","Highway KPL","Combined KPL"]]* (3.78541/1.60934)
CO2_rename2

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City KPL,Highway KPL,Combined KPL,CO2 Emission Grams/Km,Fuel Cost/Year
0,Dutton,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,324.831736,1950
1,Dutton,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
2,Dutton,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,345.133719,2100
3,Dutton,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550
4,Dutton,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,Dutton,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35948,Dutton,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,150.993575,1100
35949,Dutton,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100
35950,Dutton,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,152.857693,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,158.450048,1150

        City KPL  Highway KPL  Combined KPL
0      42.338710    39.986560     39.986560
1      30.577957    30.577957     30.577957
2      37.634409    39.986560     37.634409
3      30.577957    30.577957     30.577957
4      32.930108    49.395162     37.634409
...          ...          ...           ...
35947  79.973119    89.381722     84.677421
35948  79.973119    89.381722     84.677421
35949  79.973119    89.381722     84.677421
35950  79.973119    91.733872     84.677421
35951  75.268818    91.733872     82.325270

[35952 rows x 3 columns]

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [ ]:
# 1.1 How many car makers are there? How many models? Which car maker has the most cars in the dataset?
num_makers= len(df_cars["Make"].unique())
print(f'There are {num_makers} makers.')

# 1.2 How many models?
num_models = len(df_cars["Model"].unique())
print(f'There are {num_makers} models.')

# 1.3 Which car maker has the most cars in the dataset?
most_car = df_cars["Make"].value_counts()
most_car_maker = most_car.idxmax() # idxmax get the name(index) of maximum value
print(f'{most_car_maker} has the most cars.')

In [ ]:
# 2.1 When were these cars made? 

most_car_filter = df_cars["Make"].str.startswith("Chevrolet") #str.startswith() check if a string starts with a specified substring.
df_cars.loc[most_car_filter, ["Make",'Model', 'Year']].sort_values(by="Year") # sort_values(by="") function can sort the column by name

# 2.2 How big is the engine of these cars?
most_car_filter = df_cars["Make"].str.startswith("Chevrolet")
df_cars.loc[most_car_filter, ["Make",'Model', 'Engine Displacement']].sort_values(by="Engine Displacement")

In [ ]:
# 3.What's the frequency of different transmissions, drivetrains and fuel types?
fre_trans = df_cars["Transmission"].value_counts()

In [ ]:
fre_dri = df_cars["Drivetrain"].value_counts()

In [ ]:
fre_types =  df_cars["Fuel Type"].value_counts()

In [ ]:
# 4.What's the car that consumes the least/most fuel?
rank_all = df_cars.sort_values(by="Fuel Barrels/Year",ascending= False)# ascending= False (high-low)
max_cost = rank_all["Fuel Barrels/Year"].max()
max_cost
min_cost = rank_all["Fuel Barrels/Year"].min()
min_cost

# consumes the most 
car_consume_most =rank_all.loc[ rank_all["Fuel Barrels/Year"] == max_cost]
car_consume_most
car_consume_most_name = car_consume_most["Make"].unique()[0] # [0]前面是一个array
car_consume_most_name
print(f'{car_consume_most_name} consumes the most fuel.')

In [ ]:
# consumes the least 
car_consume_least =rank_all.loc[ rank_all["Fuel Barrels/Year"] == min_cost]
car_consume_least
car_consume_least_name = car_consume_least["Make"].unique()[0] # [0]前面是一个array
car_consume_least_name
print(f'{car_consume_least_name} consumes the least fuel.')

<b> (Optional)

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [ ]:
emissions_mean = df_cars.groupby('Make')['CO2 Emission Grams/Mile'].mean().sort_values(ascending=False).idxmax()
print(f'{emissions_mean} has the worse CO2 Emissions on average.')

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [ ]:
## Your Code is here 
CO2_rename.groupby('Is Auto?')['CO2 Emission Grams/Km'].mean()
print(f'Automatic transmission consumes more fuel than cars with manual transmission on average.')

In [ ]:
# series has index, array doesn't have it. 
# array + index = series /series +column name= dateframe